Add integration tests
canonical/nats-operator pull request #28
Opened 2023-10-10 12:13 UTC by jat-canonical

2023-10-12 18:37 UTC, morphis requested changes

2023-10-12 18:37 UTC, morphis commented on tests/integration/relation_tests/test_clustering.py
> +                num_units=2,
Lets use 3 instead of 2 as typically odd numbers are used in production.

2023-10-12 18:37 UTC, morphis commented on tests/integration/relation_tests/application-charm/src/charm.py
> +    def _on_client_relation_changed(self, event):
If I understand this correct, the idea is to let the relation fail and the unit set to `error` status to indicate the test has failed?

2023-10-12 18:37 UTC, morphis commented on tests/integration/relation_tests/application-charm/src/charm.py
> +        loop.run_until_complete(_verify_connection(url, connect_opts))
Aren't we receiving multiple URLs in case of a NATS cluster? In that case we need to verify each endpoint individually.

2023-10-12 18:37 UTC, morphis commented on tests/integration/relation_tests/test_relations.py
> +        await check_relation_data_existence(
Can't we move this into the clustering test to avoid redeployment?

2023-10-12 18:37 UTC, morphis commented on tox.ini
Can we have some explicit instructions in `CONTRIBUTING.md` on how to run the integration tests and also describe preconditions (e.g. a Juju controller, ..)

2023-10-13 09:03 UTC, ajanon commented on .github/workflows/build-and-test.yaml
> +          python-version: '3.11'
Shouldn't we run on 3.10 as that's what is by default on jammy?

2023-10-13 09:06 UTC, ajanon commented on tests/integration/relation_tests/application-charm/src/charm.py
> +            await client.publish("test", b"testing")
Shouldn't we also use the `channel_name` and `message` variables here too?
```suggestion
            sub = await client.subscribe(channel_name)
            await client.publish(channel_name, message)
```
Am I misunderstanding something?

2023-10-13 09:11 UTC, ajanon commented on tox.ini
> +    nats-py==2.4
Shouldn't it be 2.4.0, same as in tests/integration/relation_tests/application-charm/requirements.txt?
Also, shouldn't there be `ops==2.6.0` also?

2023-10-18 09:48 UTC, ajanon requested changes

2023-10-18 09:48 UTC, ajanon commented on src/relations/cluster_peers.py
> +            self._ingress_address = ipaddress.ip_address("0.0.0.0")
Shouldn't this `ipaddress.ip_address("::")` to listen for both IPv4 and IPv6?
As-is, I think this only listens on all IPv4 addresses. WDYT?

2023-10-18 09:48 UTC, ajanon commented on src/relations/natsclient_provider.py
> +            self._listen_address = ipaddress.ip_address("0.0.0.0")
As above: shouldn't this `ipaddress.ip_address("::")` to listen for both IPv4 and IPv6?
As-is, I think this only listens on all IPv4 addresses. WDYT?

2023-10-20 12:08 UTC, morphis approved these changes
LGTM

2023-10-20 12:09 UTC, merged